include:
  # - local: '.gitlab/ubuntu/ubuntu_*.yml'
  - local: '.gitlab/common.yml'
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - deps
  - build
  - test
  - deploy

variables:
  jfrogtag: 'docker_jfrog'

# {{{ ubuntu:gnu:
# {{{ ubu:deps
ubu:deps:
  stage: deps
  extends: .deps-ubu-gnu
  image: debian:testing-slim
  tags: 
    - $jfrogtag
  script:
    - echo "empty stage for a better display of deps"
  variables:
    PERSIST_IMAGE_NAME: debian:testing-slim
# }}}
# }}}
