include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - sphexa_build
  # - sphexa_run

sph-build-cuda13-sm90-debug:
  stage: sphexa_build
  # image: $MYUENV
  image: prgenv-gnu/26.3:v1
  extends: [.uenv-runner-daint-gh200]
  variables:
    SLURM_TIMELIMIT: '00:02:00'
    SLURM_JOB_NUM_NODES: 1
    SLURM_JOB_RESERVATION: 'uss140-shs131-nv590-staging'
    SLURM_GPUS_PER_NODE: 4
    SLURM_JOB_ACCOUNT: 'djenkssl'
    # PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/sphexa_cuda13_debug:${CI_COMMIT_SHORT_SHA}
    # WITH_UENV_VIEW: 'spack'  # this is not 'default' view
    WITH_UENV_VIEW: 'default'
    # SLURM_PARTITION: 'debug'
  script:
    - pwd
    # - echo "CI_PROJECT_URL=$CI_PROJECT_URL"
    # - echo "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA"
    # - echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
    # - ls -l /user-environment/
    # - ctest --test-dir /users/piccinal/sphexa.git/ci/jg/build/ -N -V
    - ctest --test-dir /users/piccinal/sphexa.git/ci/jg/build/ -j -L 01r

sph-build-cuda13-sm90-debug-08r:
  stage: sphexa_build
  # image: $MYUENV
  image: prgenv-gnu/26.3:v1
  extends: [.uenv-runner-daint-gh200]
  variables:
    SLURM_TIMELIMIT: '00:02:00'
    SLURM_JOB_NUM_NODES: 1
    SLURM_JOB_RESERVATION: 'uss140-shs131-nv590-staging'
    SLURM_GPUS_PER_NODE: 4
    SLURM_JOB_ACCOUNT: 'djenkssl'
    # PERSIST_IMAGE_NAME: ${CSCS_REGISTRY_PATH}/sphexa_cuda13_debug:${CI_COMMIT_SHORT_SHA}
    # WITH_UENV_VIEW: 'spack'  # this is not 'default' view
    WITH_UENV_VIEW: 'default'
    # SLURM_PARTITION: 'debug'
  script:
    - pwd
    # - echo "CI_PROJECT_URL=$CI_PROJECT_URL"
    # - echo "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA"
    # - echo "CI_COMMIT_SHA=$CI_COMMIT_SHA"
    # - ls -l /user-environment/
    # - ctest --test-dir /users/piccinal/sphexa.git/ci/jg/build/ -N -V
    - ctest --test-dir /users/piccinal/sphexa.git/ci/jg/build/ -j -L 08r
