FROM docker.io/nvidia/cuda:12.2.2-base-ubuntu22.04
ENV TZ Europe/Zurich

#{{{ apt: cuda/12.2 + deps 
RUN sed -i 's@archive.ubuntu.com@ubuntu.ethz.ch@' /etc/apt/sources.list \
    && echo "## apt:get update" \
    && apt update \
    && echo "## apt:get update" \
    && apt upgrade -y \
    && echo "## end"
#}}}


